export const ACTION_CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_DATA_UPDATE: 'LOGIN_DATA_UPDATE',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',

  // SET API DATA
  DATA_FETCHED_SUCCESSFUL: 'DATA_FETCHED_SUCCESSFUL',
  DATA_FETCHED_FAILED: 'DATA_FETCHED_FAILED',
};
